version: '3.8'
services:
  api:
    container_name: node_api
    restart: always
    build: .
    networks:
      - app-network
    ports:
      - ${PORT}:${PORT}
    environment:
      MONGO_URI: mongodb://${DB_NAME}:${DB_PASS}@mongodb
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mongo:latest
    restart: always
    container_name: node-db
    env_file: ./.env
    environment:
       MONGO_INITDB_ROOT_USERNAME: ${DB_NAME}
       MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app-network
    volumes:
      - db:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local
