version: '3.8'
services:
  mongo_db:
    image: mongo:latest
    restart: always
    container_name: db_container
    env_file: ./.env
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app-network
    volumes:
      - db:/data/db


  api:
    container_name: node-api
    restart: always
    env_file: ./.env
    build: .
    networks:
      - app-network
    ports:
      - ${PORT}:${PORT}
    environment:
      MONGO_URI: mongodb://mongo_db:${DB_PORT}
    links:
      - mongo_db
    volumes:
      - .:/var/www/html


networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local
